#!/bin/bash

SCRIPT_DIR=$(dirname "$(realpath "$0")")
source "$SCRIPT_DIR/const.sh"

clean-repo() {
    git checkout .
    git clean -fd
    echo "Changes removed."
}

input=""

# If in root of git repo, ask for confirmation to clean
if [[ -d .git ]]; then

    if [[ "$1" == "-y" ]]; then
        clean-repo
    else
        echo "This will discard all unsaved changes. You must be in the root of the repo to do this."
        read -p "Are you sure? [yn]: " input

        #This is zsh code
        #read "input?Are you sure? [yn]: "
        
        if [[ "$input" == "y" ]]; then
            clean-repo
        else
            echo "Aborted."
        fi
    fi

else
    echo "Not in the root of a Git repository. Aborting."
    exit 1
fi
