#!/usr/bin/env bash
# Written in [Amber](https://amber-lang.com/)
# version: 0.5.1-alpha
# We cannot import `bash_version` from `env.ab` because it imports `text.ab` making a circular dependency.
# This is a workaround to avoid that issue and the import system should be improved in the future.
trim_left__9_v0() {
    local text=$1
    command_0="$(echo "${text}" | sed -e 's/^[[:space:]]*//')"
    __status=$?
    ret_trim_left9_v0="${command_0}"
    return 0
}

trim_right__10_v0() {
    local text=$1
    command_1="$(echo "${text}" | sed -e 's/[[:space:]]*$//')"
    __status=$?
    ret_trim_right10_v0="${command_1}"
    return 0
}

trim__11_v0() {
    local text=$1
    trim_right__10_v0 "${text}"
    ret_trim_right10_v0__178_22="${ret_trim_right10_v0}"
    trim_left__9_v0 "${ret_trim_right10_v0__178_22}"
    ret_trim11_v0="${ret_trim_left9_v0}"
    return 0
}

array_shift__40_v0() {
    local array=$1
    eval "local array_deref_10=(\"\${${array}[@]}\")"
    __length_2=("${array_deref_10[@]}")
    length_10="${#__length_2[@]}"
    if [ "$(( ${length_10} == 0 ))" != 0 ]; then
        ret_array_shift40_v0=''
        return 1
    fi
    eval "local array_deref_11=\"\${${array}[0]}\""
    element_11="${array_deref_11}"
    slice_upper_3="${length_10}"
    slice_offset_4=1
    slice_offset_4=$((${slice_offset_4} > 0 ? ${slice_offset_4} : 0))
    slice_length_5="$(echo "${slice_upper_3}" '-' "${slice_offset_4}" | bc -l | sed '/\./ s/\.\{0,1\}0\{1,\}$//')"
    slice_length_5=$((${slice_length_5} > 0 ? ${slice_length_5} : 0))
    eval "local array_deref_12=(\"\${${array}[@]:\${slice_offset_4}:\${slice_length_5}}\")"
    eval "${array}=(\"\${array_deref_12[@]}\")"
    ret_array_shift40_v0="${element_11}"
    return 0
}

file_read__50_v0() {
    local path=$1
    command_6="$(< "${path}")"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_file_read50_v0=''
        return "${__status}"
    fi
    ret_file_read50_v0="${command_6}"
    return 0
}

path_3="/home/adrian/.config/git-tools"
err__64_v0() {
    local message=$1
    echo "${message}"
    exit 1
}

repo_root__66_v0() {
    command_7="$(git rev-parse --show-toplevel)"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_repo_root66_v0=''
        return "${__status}"
    fi
    ret_repo_root66_v0="${command_7}"
    return 0
}

username__67_v0() {
    file_read__50_v0 "${path_3}/secrets/username.txt"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_username67_v0=''
        return "${__status}"
    fi
    ret_username67_v0="${ret_file_read50_v0}"
    return 0
}

password__68_v0() {
    file_read__50_v0 "${path_3}/secrets/password.txt"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_password68_v0=''
        return "${__status}"
    fi
    ret_password68_v0="${ret_file_read50_v0}"
    return 0
}

git_auth__71_v0() {
    local login_key=$1
    ret_git_auth71_v0="http.extraHeader=Authorization: Basic ${login_key}"
    return 0
}

declare -r args_4=("$0" "$@")
repo_root__66_v0 
__status=$?
if [ "${__status}" != 0 ]; then
    err__64_v0 "Not inside a Git repository. Aborting."
fi
repo_root_5="${ret_repo_root66_v0}"
trim__11_v0 "${repo_root_5}"
ret_trim11_v0__9_11="${ret_trim11_v0}"
cd ${ret_trim11_v0__9_11}
__status=$?
if [ "${__status}" != 0 ]; then
    exit "${__status}"
fi
username__67_v0 
__status=$?
if [ "${__status}" != 0 ]; then
    err__64_v0 "Could not read username."
fi
username_6="${ret_username67_v0}"
password__68_v0 
__status=$?
if [ "${__status}" != 0 ]; then
    err__64_v0 "Could not read password."
fi
password_7="${ret_password68_v0}"
command_9="$(echo -n "${username_6}:${password_7}" | base64)"
__status=$?
login_key_8="${command_9}"
git_args_9=("${args_4[@]}")
array_shift__40_v0 "git_args_9"
__status=$?
git_auth__71_v0 "${login_key_8}"
ret_git_auth71_v0__22_16="${ret_git_auth71_v0}"
git -c "${ret_git_auth71_v0__22_16}" push ${git_args_9[@]}
__status=$?
if [ "${__status}" = 0 ]; then
    exit 0
fi
