#!/usr/bin/env bash
# Written in [Amber](https://amber-lang.com/)
# version: 0.5.1-alpha
# We cannot import `bash_version` from `env.ab` because it imports `text.ab` making a circular dependency.
# This is a workaround to avoid that issue and the import system should be improved in the future.
trim_left__9_v0() {
    local text=$1
    command_0="$(echo "${text}" | sed -e 's/^[[:space:]]*//')"
    __status=$?
    ret_trim_left9_v0="${command_0}"
    return 0
}

trim_right__10_v0() {
    local text=$1
    command_1="$(echo "${text}" | sed -e 's/[[:space:]]*$//')"
    __status=$?
    ret_trim_right10_v0="${command_1}"
    return 0
}

trim__11_v0() {
    local text=$1
    trim_right__10_v0 "${text}"
    ret_trim_right10_v0__178_22="${ret_trim_right10_v0}"
    trim_left__9_v0 "${ret_trim_right10_v0__178_22}"
    ret_trim11_v0="${ret_trim_left9_v0}"
    return 0
}

lowercase__12_v0() {
    local text=$1
    command_2="$(echo "${text}" | tr '[:upper:]' '[:lower:]')"
    __status=$?
    ret_lowercase12_v0="${command_2}"
    return 0
}

input_prompt__101_v0() {
    local prompt=$1
    read -p "$prompt"
    __status=$?
    command_3="$(echo $REPLY)"
    __status=$?
    ret_input_prompt101_v0="${command_3}"
    return 0
}

err__122_v0() {
    local message=$1
    echo "${message}"
    exit 1
}

cancel__123_v0() {
    local message=$1
    echo "${message}"
    exit 0
}

repo_root__124_v0() {
    command_4="$(git rev-parse --show-toplevel)"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_repo_root124_v0=''
        return "${__status}"
    fi
    ret_repo_root124_v0="${command_4}"
    return 0
}

clean_repo__133_v0() {
    git checkout .
    __status=$?
    git clean -fd
    __status=$?
    echo "Changes removed."
}

declare -r args_4=("$0" "$@")
repo_root__124_v0 
__status=$?
if [ "${__status}" != 0 ]; then
    err__122_v0 "Not inside a Git repository. Aborting."
fi
repo_root_5="${ret_repo_root124_v0}"
echo "${repo_root_5}"
command_6="$(basename ${repo_root_5})"
__status=$?
if [ "${__status}" != 0 ]; then
    err__122_v0 "Failed to determine repository name."
fi
repo_name_6="${command_6}"
trim__11_v0 "${repo_root_5}"
ret_trim11_v0__22_11="${ret_trim11_v0}"
cd ${ret_trim11_v0__22_11}
__status=$?
if [ "${__status}" != 0 ]; then
    exit "${__status}"
fi
__length_7=("${args_4[@]}")
force_7="$(( $(( ${#__length_7[@]} > 0 )) && $([ "_${args_4[0]}" != "_-y" ]; echo $?) ))"
if [ "$(( ! ${force_7} ))" != 0 ]; then
    echo "This will permanently discard ALL uncommitted changes from ${repo_name_6}."
    input_prompt__101_v0 "Are you sure? [y/N]: "
    input_8="${ret_input_prompt101_v0}"
    lowercase__12_v0 "${input_8}"
    ret_lowercase12_v0__30_12="${ret_lowercase12_v0}"
    if [ "$([ "_${ret_lowercase12_v0__30_12}" == "_y" ]; echo $?)" != 0 ]; then
        cancel__123_v0 "Aborted."
    fi
fi
clean_repo__133_v0 
