#!/usr/bin/env bash
# Written in [Amber](https://amber-lang.com/)
# version: 0.5.1-alpha
# We cannot import `bash_version` from `env.ab` because it imports `text.ab` making a circular dependency.
# This is a workaround to avoid that issue and the import system should be improved in the future.
trim_left__9_v0() {
    local text=$1
    command_0="$(echo "${text}" | sed -e 's/^[[:space:]]*//')"
    __status=$?
    ret_trim_left9_v0="${command_0}"
    return 0
}

trim_right__10_v0() {
    local text=$1
    command_1="$(echo "${text}" | sed -e 's/[[:space:]]*$//')"
    __status=$?
    ret_trim_right10_v0="${command_1}"
    return 0
}

trim__11_v0() {
    local text=$1
    trim_right__10_v0 "${text}"
    ret_trim_right10_v0__178_22="${ret_trim_right10_v0}"
    trim_left__9_v0 "${ret_trim_right10_v0__178_22}"
    ret_trim11_v0="${ret_trim_left9_v0}"
    return 0
}

lowercase__12_v0() {
    local text=$1
    command_2="$(echo "${text}" | tr '[:upper:]' '[:lower:]')"
    __status=$?
    ret_lowercase12_v0="${command_2}"
    return 0
}

input_prompt__101_v0() {
    local prompt=$1
    read -p "$prompt"
    __status=$?
    command_3="$(echo $REPLY)"
    __status=$?
    ret_input_prompt101_v0="${command_3}"
    return 0
}

repo_root__122_v0() {
    command_4="$(git rev-parse --show-toplevel)"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_repo_root122_v0=''
        return "${__status}"
    fi
    ret_repo_root122_v0="${command_4}"
    return 0
}

clean_repo__128_v0() {
    git checkout .
    __status=$?
    git clean -fd
    __status=$?
    echo "Changes removed."
}

declare -r args_4=("$0" "$@")
repo_root__122_v0 
__status=$?
if [ "${__status}" != 0 ]; then
    echo "Not inside a Git repository. Aborting."
    exit 1
fi
repo_root_5="${ret_repo_root122_v0}"
trim__11_v0 "${repo_root_5}"
ret_trim11_v0__19_11="${ret_trim11_v0}"
cd ${ret_trim11_v0__19_11}
__status=$?
if [ "${__status}" != 0 ]; then
    exit "${__status}"
fi
__length_6=("${args_4[@]}")
force_6="$(( $(( ${#__length_6[@]} > 0 )) && $([ "_${args_4[0]}" != "_-y" ]; echo $?) ))"
if [ "$(( ! ${force_6} ))" != 0 ]; then
    echo "This will permanently discard ALL uncommitted changes."
    input_prompt__101_v0 "Are you sure? [y/N]: "
    input_7="${ret_input_prompt101_v0}"
    lowercase__12_v0 "${input_7}"
    ret_lowercase12_v0__27_12="${ret_lowercase12_v0}"
    if [ "$([ "_${ret_lowercase12_v0__27_12}" == "_y" ]; echo $?)" != 0 ]; then
        echo "Aborted."
        exit 0
    fi
fi
clean_repo__128_v0 
