#!/usr/bin/env bash
# Written in [Amber](https://amber-lang.com/)
# version: 0.5.1-alpha
# We cannot import `bash_version` from `env.ab` because it imports `text.ab` making a circular dependency.
# This is a workaround to avoid that issue and the import system should be improved in the future.
split__5_v0() {
    local text=$1
    local delimiter=$2
    result_8=()
    IFS="${delimiter}" read -rd '' -a result_8 < <(printf %s "$text")
    ret_split5_v0=("${result_8[@]}")
    return 0
}

text_contains__17_v0() {
    local source=$1
    local search=$2
    result_14="$(if [[ "${source}" == *"${search}"* ]]; then
    echo 1
  fi)"
    ret_text_contains17_v0="$([ "_${result_14}" != "_1" ]; echo $?)"
    return 0
}

starts_with__23_v0() {
    local text=$1
    local prefix=$2
    result_7="$(if [[ "${text}" == "${prefix}"* ]]; then
    echo 1
  fi)"
    ret_starts_with23_v0="$([ "_${result_7}" != "_1" ]; echo $?)"
    return 0
}

ends_with__24_v0() {
    local text=$1
    local suffix=$2
    result_15="$(if [[ "${text}" == *"${suffix}" ]]; then
    echo 1
  fi)"
    ret_ends_with24_v0="$([ "_${result_15}" != "_1" ]; echo $?)"
    return 0
}

slice__25_v0() {
    local text=$1
    local index=$2
    local length=$3
    if [ "$(( ${length} == 0 ))" != 0 ]; then
        __length_4="${text}"
        length="$(( ${#__length_4} - ${index} ))"
    fi
    if [ "$(( ${length} <= 0 ))" != 0 ]; then
        ret_slice25_v0=""
        return 0
    fi
    ret_slice25_v0="$(printf "%.${length}s" "${text: ${index}}")"
    return 0
}

declare -r args_3=("$0" "$@")
remote_url_4="$(git remote get-url origin)"
browser_url_5=""
browser_6="google-chrome-stable"
starts_with__23_v0 "${remote_url_4}" "https://"
ret_starts_with23_v0__12_9="${ret_starts_with23_v0}"
starts_with__23_v0 "${remote_url_4}" "ssh:"
ret_starts_with23_v0__13_9="${ret_starts_with23_v0}"
if [ "${ret_starts_with23_v0__12_9}" != 0 ]; then
    browser_url_5="${remote_url_4}"
elif [ "${ret_starts_with23_v0__13_9}" != 0 ]; then
    split__5_v0 "${remote_url_4}" "/"
    components_9=("${ret_split5_v0[@]}")
    domain_10="${components_9[2]}"
    user_org_11="${components_9[3]}"
    repo_12="${components_9[4]}"
    lf_git_13="git.lunarflame.dev"
    text_contains__17_v0 "${domain_10}" "${lf_git_13}"
    ret_text_contains17_v0__21_16="${ret_text_contains17_v0}"
    if [ "${ret_text_contains17_v0__21_16}" != 0 ]; then
        domain_10="${lf_git_13}"
    fi
    ends_with__24_v0 "${repo_12}" ".git"
    ret_ends_with24_v0__25_16="${ret_ends_with24_v0}"
    if [ "${ret_ends_with24_v0__25_16}" != 0 ]; then
        __length_8="${repo_12}"
        slice__25_v0 "${repo_12}" 0 "$(( ${#__length_8} - 4 ))"
        repo_12="${ret_slice25_v0}"
    fi
    browser_url_5="https://${domain_10}/${user_org_11}/${repo_12}"
fi
echo "Opening ${browser_url_5}..."
${browser_6} ${browser_url_5}
__status=$?
if [ "${__status}" != 0 ]; then
    echo "Could not open url."
fi
