import { trim } from "std/text"
import { array_shift } from "std/array"
import * from "const.ab"

main(args) {
    let repo_root = repo_root() failed:
        err("Not inside a Git repository. Aborting.")

    $ cd {trim(repo_root)} $?

    const username = username() failed:
        err("Could not read username.")

    const password = password() failed:
        err("Could not read password.")

    const login_key = trust $ echo -n "{username}:{password}" | base64 $

    let git_args = args
    trust array_shift(git_args)

    $ git -c "{git_auth(login_key)}" push {git_args} $ succeeded:
        exit 0
}
