import { trim } from "std/text"
import { username, password, gitea_url, repo_root, err } from "const.ab"

main(args) {
    let repo_root = repo_root() failed:
        err("Not inside a Git repository. Aborting.")

    $ cd {trim(repo_root)} $?

    const username = username() failed:
        err("Could not read username.")

    const password = password() failed:
        err("Could not read password.")

    const login_key = trust $ echo -n "{username}:{password}" | base64 $

    $ git -c http.extraHeader="Authorization: Basic {login_key}" push {args} $ succeeded:
        exit 0
}
