import { env_var_get } from "std/env"
import { starts_with, ends_with, split, slice, text_contains } from "std/text"
import { repo_root, err } from "const.ab" 

main(args) {

    repo_root() failed:
        err("Not inside a Git repository. Aborting.")

    const remote_url = trust $ git remote get-url origin $

    let browser_url = ""

    const browser = "xdg-open"

    if {
        starts_with(remote_url, "https://"): browser_url = remote_url
        starts_with(remote_url, "ssh:") {
            let components = split(remote_url, "/")

            let domain = components[2]
            let user_org = components[3]
            let repo = components[4]

            if text_contains(domain, "lunarflame.dev"):
                domain = "git.lunarflame.dev"

            if ends_with(repo, ".git"):
                repo = slice(repo, 0, len(repo) - 4)

            browser_url = "https://{domain}/{user_org}/{repo}"
        }
    }

    echo "Opening {browser_url}..."
    silent $ {browser} {browser_url} $ failed(code):
        err("Could not open url: {code}")
}
