import { env_var_get } from "std/env"
import { starts_with, ends_with, split, slice, text_contains } from "std/text"

main(args) {
    const remote_url = trust $ git remote get-url origin $

    let browser_url = ""

    const browser = "google-chrome-stable"

    if {
        starts_with(remote_url, "https://"): browser_url = remote_url
        starts_with(remote_url, "ssh:") {
            let components = split(remote_url, "/")

            let domain = components[2]
            let user_org = components[3]
            let repo = components[4]

            const lf_git = "git.lunarflame.dev"
            if text_contains(domain, lf_git) {
                domain = lf_git
            }

            if ends_with(repo, ".git") {
                repo = slice(repo, 0, len(repo) - 4)
            }

            browser_url = "https://{domain}/{user_org}/{repo}"
        }
    }

    echo "Opening {browser_url}..."
    $ {browser} {browser_url} $ failed {
        echo "Could not open url."
    }
}
